DDCNL-7901
hmrc/tai-frontend pull request #1275
Opened 2023-10-10 16:37 UTC by SandeepUmredkar

- [ ] Unit tests passing
- [ ] Coverage reached
- [ ] Acceptance tests passing
- [ ] Reviewed

2023-10-13 06:35 UTC, grantrobson commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +                if (error.statusCode == BAD_REQUEST) {
Minor thing but match is cleaner than if

2023-10-13 06:36 UTC, grantrobson commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +    val httpCall = if (timeoutInSec.isDefined) {
Cleaner to use map + fold as it avoids using .get

2023-10-13 06:36 UTC, grantrobson commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +      http.put(url"$url")(hc).withBody(data).transform(_.withRequestTimeout(timeoutInSec.get.seconds))
Cleaner to use map + fold

2023-10-20 15:32 UTC, pascal22p requested changes

2023-10-20 15:32 UTC, pascal22p commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +  def getFromApiV2(url: String, timeoutInSec: Option[Int] = None)(implicit
Make the type works for you. Use a Duration for timeoutInSec

2023-10-23 09:11 UTC, SandeepUmredkar commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +            )
The reason is the handleResponse is deprecated hence it shows warning and it asks to use handleResponseEither in that place. So I changed it. I have ran all the tests and figured if that works this should be fine to change. Happy to revert.

2023-10-30 11:26 UTC, pascal22p commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +            )
Keep the deprecated method as is. The deprecation warning is to prevent further use of those methods.

2023-10-31 11:43 UTC, SandeepUmredkar commented on app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> +            )
Done

2023-10-31 11:54 UTC, pascal22p submitted a review, later dismissed

2023-11-03 07:45 UTC, grantrobson approved these changes

2023-11-06 07:36 UTC, merged