DDCNL-2427
hmrc/tai-frontend pull request #732
Opened 2020-08-21 15:21 UTC by oc-ste

- [x] Unit tests passing
- [x] Coverage reached
- [x] Acceptance tests passing
- [x] Reviewed

2020-08-24 12:50 UTC, shikkhasingh approved these changes

2020-09-07 12:36 UTC, shikkhasingh requested changes

2020-09-07 12:36 UTC, shikkhasingh commented on test/views/html/IncomeSourceSummaryViewSpec.scala
> +      "rti is unavailable display rti down messages for pensios" in {
typo in the test name

2020-09-07 12:36 UTC, shikkhasingh commented on conf/messages
> -tai.rti.down.ceased_employments = We cannot show this information at this time. Try again later to view employments that have ended.
Can we please update the references of this message key as well?
I can see two of them inside the code

2020-09-07 12:36 UTC, shikkhasingh commented on conf/messages.cy
> +tai.rti.down.updatePension=You cannot update or remove this pension at this time. Try again later.
welsh translation not available yet ?

2020-09-08 10:30 UTC, oc-ste commented on conf/messages.cy
> +tai.rti.down.updatePension=You cannot update or remove this pension at this time. Try again later.
Not yet

2020-09-08 10:35 UTC, shikkhasingh approved these changes

2020-09-11 11:23 UTC, merged