DDCNL-3547
hmrc/tai-frontend pull request #774
Opened 2021-03-19 09:37 UTC by struong

- [x] Unit tests passing
- [x] Coverage reached
- [ ] Acceptance tests passing
- [ ] Reviewed

2021-03-22 11:37 UTC, shikkhasingh requested changes
Are we using gatekeeper.scala.html anywhere, If not can we please delete it?

2021-03-22 11:37 UTC, shikkhasingh commented on conf/messages
>  label.opens_in_a_new_window=(opens in a new window)
This key can be deleted as it is no longer being used.

2021-03-22 14:31 UTC, shikkhasingh approved these changes

2021-04-07 13:23 UTC, shikkhasingh approved these changes

2021-04-22 14:46 UTC, struong commented
test this please

2021-05-07 14:59 UTC, merged